{% set name = "lmdbm" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmdbm-{{ version }}.tar.gz
  sha256: 2c1d0dd995b074fe72154cc59c9221b348afccb237e2994aa0a463d6621a4db9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
    - flit-core
  run:
    - lmdb
    - typing-extensions >=4
    - python >=3.6
    - python-lmdb

test:
  imports:
    - lmdbm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Dobatymo/lmdb-python-dbm
  summary: Python DBM style wrapper around LMDB (Lightning Memory-Mapped Database)
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
