{% set name = "lmdbm" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmdbm-{{ version }}.tar.gz
  sha256: a4b6a2c0700d7d3e3c09f902c63a4fb3356662d171ce92bdde0803e02e25c859

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - python-lmdb

test:
  imports:
    - lmdbm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Dobatymo/lmdb-python-dbm
  summary: Python DBM style wrapper around LMDB (Lightning Memory-Mapped Database)
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
